### ISSUE TITLE
photon-ui - support multiple ::ui/keychords

### ISSUE THREAD

**Issue by den1k** [hyperfiddle/electric#15]
curious how `::ui/keychords` and `::ui/keychord-event` would work for multiple chords since it seems that `keychord-event` does not disambiguate between different chords. for example, what if another chord besides enter is added to the keychord set? how does that become apparent in keychord-event?

https://github.com/hyperfiddle/photon/blob/b3404128980c810e62ea24890763c3ac93463199/src-docs/user/demo_4_chat.cljc#L15-L19

alternatively, maybe both can be combined, like

```clojure
{::ui/on-keychord {"enter" (p/fn [_] '...)
                   "shift+enter" (p/fn [_] '...)}}
```

**Comment by dustingetz** [comment]
Closing as we removed this API in lieu of a lower level API for bespoke event handlers
