### ISSUE TITLE
What does "Multiplayer-native" mean?

### ISSUE THREAD

**Issue by oscarhermoso** [hyperfiddle/electric#22]
Might need a clarifiaction, I tried googling and couldn't find anything

Thanks 🙂

**Comment by xificurC** [comment]
Hi @oscarhermoso, thanks for the question!

It means the app you build will automatically sync between concurrent users. You can see this when running [the starter app](https://github.com/hyperfiddle/electric-starter-app), just open 2 tabs and anything you write in one tab will automatically show up in the other.

What do you think we could add to the readme to clarify this to the users?

**Comment by bbss** [comment]
What happens on conflicts? How does it compare to CRDT's?

**Comment by dustingetz** [comment]
Transactional vs conflict-free is a userland choice; streaming a mouse coordinate signal, for example, is not transactional. If userland wants to write to a shared reference, you'll need to provide a conflict resolution strategy, many libraries to choose from. The default choice of "atom with reset!" encodes a race, "atom with swap!" is perhaps the simplest possible transaction.

**Comment by dustingetz** [comment]
Take the demo-chat for example - if two users send a message at the same time, the atom serializes the events and they race. https://github.com/hyperfiddle/electric/blob/master/src-docs/user/demo_4_chat.cljc#L27
