### ISSUE TITLE
add SVG support to electric-dom

### ISSUE THREAD

**Issue by den1k** [hyperfiddle/electric#31]
What is in the way of adding SVG and its child elements to dom2?

**Comment by dustingetz** [comment]
https://github.com/formicagreen/electric-clojure-painter also needs SVG

**Comment by ggeoffrey** [comment]
Not much, we need to add support for namespaced elements (and maybe attributes)

**Comment by den1k** [comment]
Would be great to have this. I'm currently doing a lot of wacky things with hiccup/reagent or serializing SVG.

**Comment by den1k** [comment]
is this all that would need to change? 

https://github.com/hyperfiddle/electric/blob/master/src/hyperfiddle/electric_dom2.cljc#L34-L41

**Comment by dustingetz** [comment]
There are some gotchas, pasting from our slack:

> The value attribute is used as the initial value of the value property. `domNode.setAttribute("value", "foo")` will not necessarily set the input’s value property, and therefore not necessarily set the input’s content.
> Also note goog.dom.setProperties doesn’t work for some properties or attributes I can remember at least these:
> * data-…  attributes
> * list property
> * anything namespaced, like SVG

**Comment by dustingetz** [comment]
![mac_window_options](https://user-images.githubusercontent.com/124158/221417985-e99d7aa1-3518-4fac-983a-fc010161930d.svg)
![safari-pinned-tab](https://user-images.githubusercontent.com/124158/221417999-ffa55c18-72a9-470e-9226-8dac092f1885.svg)

**Comment by dustingetz** [comment]
Looks like half a day of work, perhaps best done in a separate namespace to avoid any API commitments. Dennis if you want to take a whack at contributing this, we can probably support you
