### ISSUE TITLE
Links to demos are broken

### ISSUE THREAD

**Issue by eladve** [hyperfiddle/electric#35]
In the main readme.md, several of the links to demos are broken. For example, the following links are broken:
[Todos Basic](https://github.com/hyperfiddle/electric/blob/master/src-docs/user/todos_simple.cljc)
[Full-stack webview with datascript](https://github.com/hyperfiddle/electric/blob/master/src-docs/user/demo_4_webview.cljc)

**Comment by dustingetz** [comment]
Thank you, fixed!
