### ISSUE TITLE
Passing server atom behavior

### ISSUE THREAD

**Issue by joshcho** [hyperfiddle/electric#49]
I have the following electric function:

```
(e/defn Toggle [task-id]
  (let [toggled
        (e/server (:task/toggled (d/entity db task-id)))]
    (ui/button
      (e/fn []
        (js/console.log "Toggling " task-id)
        (e/server
         (d/transact! !conn [{:db/id task-id
                              :task/toggled
                              (not (:task/toggled (d/entity @!conn task-id)))}])))
      (dom/props {:class "ml-1 btn btn-xs w-fit px-1"})
      (dom/on "click" (e/fn [e]
                        (.stopPropagation e)))
      (if toggled
        (svg/svg (dom/props {:width  10
                             :height 10})
                 (SVGVerticalLine.)
                 (SVGHorizontalLine.))
        (svg/svg (dom/props {:width  10
                             :height 10})
                 (SVGHorizontalLine.))))))
```

The button toggles, but hangs (I suspect some kind of cycle). But interestingly, if you rewrite the `e/server` expression inside `e/fn` like the following, everything works fine:

```
        (e/server
         (do (d/transact! !conn [{:db/id task-id
                                  :task/toggled
                                  (not (:task/toggled (d/entity @!conn task-id)))}])
             nil))
```
What's the expected behavior when passing server atom?

**Comment by xificurC** [comment]
`d/transact!` returns tx-data that cannot be serialized, so returning `nil` is objectively better in this case. But I don't see any obvious reason why the rewrite would fix your code. Can you share a minimal repro repository to further investigate?

**Comment by joshcho** [comment]
Hm, so should this work even if I don't return nil? I am using the workaround atm.

**Comment by dustingetz** [comment]
Yeah, the snippet as posted should not hang per my read (assuming `task-id` is invariant)

**Comment by joshcho** [comment]
Got it. I will try a bit to figure it out. Thank you both.
