### ISSUE TITLE
[Suggestion] Introduce the concept of SanitizedString to the world

### ISSUE THREAD

**Issue by elimisteve** [hyperfiddle/electric#51]
Hi there!

I love the idea of Hyperfiddle and have thought for years that we should be able to declare how a new app works in one place and then derive from that the frontend and backend code (in whichever languages are best suited to the given context). It's an accident of history that building a single app requires gluing together a hodgepodge of different technologies that don't know each other even exist (and don't know how to work well together).

## SanitizedString / SafeString / TrustedString, SomethingString

I completely understand that your programming model does not introduce new possibilities for SQL injection or the like; the security model is not worse than the status quo.

Here's how it can be better. I am confident that you all are forward-looking enough to do something with the following idea, assuming you agree it's a good one:

**What if using a String (which probably contains user input) in a function that requires a SanitizedString were a compile-time type error?** Then the _type system_ could prevent SQL injection!

This should be the status quo in every language, but of course I've never seen it done.

I would love to see Hyperfiddle be the first to adopt this idea!

**Comment by dustingetz** [comment]
We will keep this in mind if we spot an opportunity to something like this
