### ISSUE TITLE
incremental compilation

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/electric#54]
Coming soon! Currently, the Electric compiler is implemented as a full-program analysis which means a full rebuild is required for each minor change to Electric source code. This can quickly build up to 20-30s compile times for apps with 2000 LOC of Electric. Fixed by rebuilding the Electric compiler to compile one def at a time.

**Comment by avocade** [comment]
Can't wait, currently the biggest impediment to productivity (>15s recompilations on a MacBook Pro M1 Max w 64GB RAM).

🙌🏻
